### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by tomginsberg** [silverAndroid/drivetest-ca-availabilities#1]
Hi, I was trying to implement something similar when I came across this. Looks like DriveTest updated their website and I'm not really sure how the captcha is working now.

If you have any insight to share let me know and I'll try and update your script.

**Comment by nergmada** [comment]
So I think I've fixed this problem, I mean the theory side of it. From what I can see the dmid cookie that you need to make this script work is delivered when this link is loaded. So what you need to do is do a get request first against this link, strip out the dmid cookie and then post with that

https://drivetest.ca/ng/dt-booking

**Comment by nisarg89** [comment]
It would be amazing if someone with a better grip on this can post a fixed version of the script. I tried doing this for some time (now there is an emailToken which is embedded in a link sent to your email when you verify your email). But I couldn't get a valid json response by posting to any of the following:

https://drivetest.ca/booking/v1/driver/email/token
https://drivetest.ca/booking/v1/driver/emailToken

both of which seem to be used at some point in the process.

**Comment by silverAndroid** [comment]
I've found a better way to do this using Puppeteer.js (it'll launch an instance of Chrome tho). I'll probably be pushing a version that'll make sure not to overload the site with requests when searching as soon as I can 😊

**Comment by nisarg89** [comment]
Wow, that's amazing. Thanks so much. Please post a comment here once you push 👍

**Comment by vdyagilev** [comment]
hi has there been any progress made on the project? I can help bring it to v1.0 if need be

**Comment by silverAndroid** [comment]
Just an update, the end goal is to make a web app out of it which I am working with someone to make. As a temporary solution, I'll be pushing up a CLI tool that can be packaged up into a binary and I'll be pushing that up soon! The last bit remaining is to package it up into a nice little executable.

**Comment by silverAndroid** [comment]
First version of the CLI should be up soon, sorry for taking so long to develop this! I've been juggling this with work, I'm hoping to have the first version ready to use within the next 2 weeks.

**Comment by Aadi04** [comment]
Any update on the CLI?

**Comment by silverAndroid** [comment]
Hi everyone, I've (finally) creating a working first release (which you can find [here](https://github.com/silverAndroid/drivetest-ca-availabilities/releases/tag/v1.0)). Sorry for it taking so long. Could you take a look at the [updated README](https://github.com/silverAndroid/drivetest-ca-availabilities/pull/4) and give any feedback you have on if there's any instructions that don't make sense or could be clearer? Thanks for your patience.
