### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by benbick96** [silverAndroid/drivetest-ca-availabilities#10]
[drivetest-2021-05-18_08-00-51.log](https://github.com/silverAndroid/drivetest-ca-availabilities/files/6501117/drivetest-2021-05-18_08-00-51.log)
Selects a testing location and clicks forward through the months as far as it can, seems to happen with or without a current appointment booked and no matter what the months/location/radius are set to.
Thank you!

**Comment by silverAndroid** [comment]
Hmm that's strange, I'll take a look

**Comment by Sandy4161** [comment]
having the exact same issue
[drivetest-2021-07-05_17-10-08.log](https://github.com/silverAndroid/drivetest-ca-availabilities/files/6766218/drivetest-2021-07-05_17-10-08.log)

**Comment by silverAndroid** [comment]
I made a new release that might've fixed this issue. If it does, can you please let me know?

**Comment by silverAndroid** [comment]
Closing as stale
