### ISSUE TITLE
Instance exits immediately after logging in

### ISSUE THREAD

**Issue by BigBoy519** [silverAndroid/drivetest-ca-availabilities#12]
After the recent update of the Drivetest website, I found that the scraper no longer passes the login phase on my end. The console log simply states "Finding available times for a G2 exam" then promptly exits. Is this reproducible on your end?

**Comment by afnanahmad** [comment]
+1 I'm having similar issue.

**Comment by silverAndroid** [comment]
I'll take a look next week, as I'm a bit busy this week

**Comment by saseeja** [comment]
Also, since the site for drivetest is mostly down and the latency has increased. Could you please increase the timeout as well?

**Comment by saseeja** [comment]
> After the recent update of the Drivetest website, I found that the scraper no longer passes the login phase on my end. The console log simply states "Finding available times for a G2 exam" then promptly exits. Is this reproducible on your end?

You can increase the timeout in the scraper.ts that't what I did. It waited for login but then as soon as it selected for G exam the process got exit and reason logged in the log file

**Comment by silverAndroid** [comment]
Sorry for taking so long for an update. Over the past couple of weeks, I've been trying to get in to the site myself to try and resolve this issue but with no luck 🙃😞 I'll keep trying but as long as the site keeps returning errors to me, it'll be difficult to fix. Thanks for your patience.

**Comment by silverAndroid** [comment]
Sorry for taking so long, I made a new release that hopefully fixes this issue! If it does, can you please let me know?

**Comment by silverAndroid** [comment]
Closing as stale
