### ISSUE TITLE
No dates written to terminal

### ISSUE THREAD

**Issue by proactivematter** [silverAndroid/drivetest-ca-availabilities#14]
Hey, first off, thanks for this tool!

I can see dates available as the screen flashes through the months, but nothing is written to the terminal.

Also, everything just stops (presumably when it finishes scanning through all available test locations in the specified radius) - I thought this was supposed to keep running endlessly looking for dates? Or do I have to do it manually every so often?

Also, no errors on the terminal or log.

**Comment by silverAndroid** [comment]
Hey @proactivematter, it's currently a known [issue](https://github.com/silverAndroid/drivetest-ca-availabilities/issues/12), I'll take a look at these issues tomorrow evening or sometime this week.

**Comment by proactivematter** [comment]
Oh yeah I guess that's the same, actually. Awesome thank you @silverAndroid !

**Comment by somilaseeja** [comment]
Yeah same here. I tweaked the code a bit and made it work like on the name of the drive test center and it still doesn’t work with more than one city. I can pass multiple cities name but hangs at the second.

**Comment by silverAndroid** [comment]
Will be tracking this issue as part of #12
