### ISSUE TITLE
Recaptch issue

### ISSUE THREAD

**Issue by somilaseeja** [silverAndroid/drivetest-ca-availabilities#15]
I am facing this recaptcha issue sometimes and once it starts coming it never goes.  If you can handle this please? It happens just when we hit the submit button. The captcha response goes in the request to the verify driver email. But most of the time recaptcha validation gets failed and verify email returns error. I checked this with launch option debug: true

**Comment by silverAndroid** [comment]
Yea not a lot I can do about getting around Recaptcha, especially since they're using v3. If they were still on v2, there might've still been a chance.

**Comment by vikas-prabhakar** [comment]
@silverAndroid thanks for this code. I was using your code but unfortunately it was asking recaptch in loop. Kindly let me know but I am missing.
I was checking with your latest code changes
