### ISSUE TITLE
Program opens then immediately shuts down, empty log

### ISSUE THREAD

**Issue by Sandy4161** [silverAndroid/drivetest-ca-availabilities#16]
Hi, this is probably a really dumb issue. I am a non-coder but have lately been fed up trying to book a G test manually and I found your project through a Google search. 

I downloaded the windows version of your executable. However, when I run it (normally or as admin) a command interface briefly pops up then closes. A blank log file is then created in the directory with the exe.  

This sounds like an amazing tool and I would love to be able to use it. Any help would be much appreciated.

**Comment by silverAndroid** [comment]
Will be tracking this issue as part of #12
