### ISSUE TITLE
CLI Arguments not working with npm

### ISSUE THREAD

**Issue by NimishVerma** [silverAndroid/drivetest-ca-availabilities#18]
Using npm instead of yarn, I know it is not recommended. But it throws an error even if I pass the CLI argument `--licenceType G`.
`Cannot read property 'licenceType' of undefined'. I am guessing it is trying to load config which throws undefined?

**Comment by silverAndroid** [comment]
The reason that's happening is because the config.json is invalid (most likely need to remove the comments from the JSON). I forgot to throw an error when it fails to parse the JSON but that's why.
