### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by ixpyro** [silverAndroid/drivetest-ca-availabilities#27]
It seems that perhaps with the recent additions of the new offsite locations, the program is looking up incorrect sites for availabilities. For example, I've noticed that the automated window was actually searching in Blind River while printing results for Brampton, and Marathon instead of Mississauga, etc.

**Comment by silverAndroid** [comment]
Hi @ixpyro, I tried to reproduce this issue but was unable to. I know that occasionally the script halts after selecting the next location because it's waiting for the response to return (after selecting a new location). Is it possible that's what happened for you?

**Comment by silverAndroid** [comment]
Closing as stale
