### ISSUE TITLE
Ability to keep checking more than once?

### ISSUE THREAD

**Issue by tn133** [silverAndroid/drivetest-ca-availabilities#29]
Hello, I really appreciate the work that's gone into this tool, and I've been able to get it working. However, I'm wondering if it would be possible to alter it to continue checking after going through the list of locations once. 

Right now, the tool goes through the list of specified locations, and then closes Chromium if no time slots are found with `{"level":50,"time":1628982695093,"pid":1843,"hostname":"MacBook-Pro.local","msg":"No timeslots found"}` displayed in the terminal. I am suggesting adding the option to go back to the beginning of the list of locations and continue checking them throughout that 45-minute session until something comes up. I keep hearing about people who get appointments by chance, randomly checking and a single appointments comes up.

This would be helpful to check smaller centres that don't have a ton of new appointments added in bulk, but only one or two when a cancellation comes up. 

(I am running on Mac OS X 10.15.7, but I assume this function would be the same regardless of platform.)

**Comment by silverAndroid** [comment]
@tn133 If I were to implement this, would you prefer the script to stop when it does find timeslots or just continue looking?

**Comment by wajihalam** [comment]
I think a functionality for the user to be able to add how frequently they want the program to check automatically. For example: the wait time in between searches can be 30 min, 1 hour, etc. This would help?

**Comment by tn133** [comment]
Yes, that would be helpful. I would like it to keep looking through the locations.

**Comment by kjstart** [comment]
Please stop the app after session timeout. :)

**Comment by silverAndroid** [comment]
Continuous searching can now be enabled by passing the option `--enableContinuousSearching`
