### ISSUE TITLE
Location error

### ISSUE THREAD

**Issue by h4harsimran** [silverAndroid/drivetest-ca-availabilities#31]
**Describe the bug**
It keeps giving me same error no matter what location arg I provide.
`PS C:\driver> yarn start -l 43.7777392,-79.4348292
yarn run v1.22.11
$ node cli.js -l "43.7777392 -79.4348292"
error: option '-l, --location <location>' argument '43.7777392 -79.4348292' is invalid. location coordinates must follow format <latitude>,<longitude>!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\driver>`

I already have other arguments in json config file.

**Comment by silverAndroid** [comment]
@h4harsimran you're missing a comma for the location,  it should be "43.7777392,-79.4348292"

**Comment by h4harsimran** [comment]
I was adding the comma, look in the first line where I Passed the argument

**Comment by silverAndroid** [comment]
Oh interesting, I'll take a look at this

**Comment by h4harsimran** [comment]
I did pass through this by deleting the section that was proving the error in code. Its in "isInLicenseRange" file where you give a condition to check the length of coordinates list I think. But now its stuck at logging in.

**Comment by silverAndroid** [comment]
What version of Windows are you using, and which command line client are you using (ie. Powershell, Command Prompt, etc.)? I'm having trouble reproducing this issue on my machine.

**Comment by silverAndroid** [comment]
Also, what version of Node?

**Comment by h4harsimran** [comment]
Powershell on Windows 10 with Node v14.17.5

**Comment by h4harsimran** [comment]
looks like there is some issue with their website now, its not even allowing me to login manually, will try later and revert back with update.

**Comment by silverAndroid** [comment]
Seems like the original issue is an issue with yarn dropping the comma when passing the location argument. If you surround it with quotes, it works fine `yarn start -l "43.7777392,-79.4348292"`
