### ISSUE TITLE
timeout exceeded while waiting for event?

### ISSUE THREAD

**Issue by BLecour** [silverAndroid/drivetest-ca-availabilities#9]
i get this error about 30 seconds after launching the program where it seems to be stuck on the screen with all the locations on the map. i attached my log as well in case you want to take a look
[drivetest-2021-05-18_00-36-17.log](https://github.com/silverAndroid/drivetest-ca-availabilities/files/6498450/drivetest-2021-05-18_00-36-17.log)

**Comment by silverAndroid** [comment]
I'll take a look next week as I've been a bit busy. Should be a quick fix.

**Comment by silverAndroid** [comment]
Sorry for taking so long, I made a new release that hopefully fixes this issue. If it does, can you please let me know?

**Comment by silverAndroid** [comment]
Closing as stale
